### ISSUE TITLE
Problema con el primer acceso como admin

### ISSUE THREAD

**Issue by juanlurivas** [IESMonterroso/intranet#10]
Hola,

Lo primero, agradeceros el esfuerzo de mantener y compartir el trabajazo hecho con la intranet. El año pasado tuve la oportunidad de verla en funcionamiento en un IES de Marbella y este año me gustaría ponerla en mi centro.

El problema que tengo es que después de descargar, copiar en el servidor, darle permisos y configurar la intranet por primera vez, cuando termina y aparece la contraseña de admin para que inicie sesión por primera vez, intento iniciar sesión y poniendo usuario "admin" y la contraseña generada por el sistema, dice que usuario o contraseña incorrecto. He probado con 3 releases diferentes de la intranet, y nada. He probado en servidor público y en local obteniendo los mismos resultados.
Veo que las tablas de la bbdd se crean, pero no consigo adivinar cómo entrar si el password que aparece en pantalla cuando lo pongo lo da como incorrecto.

A ver si me podéis iluminar en algo que esté haciendo mal en el proceso :)

Gracias por adelantado!

Juanlu.

**Comment by mgarcia39** [comment]
Hola Juan.

Habrá que mirar el asunto que comentas. No tenemos noticias de problemas en
el login inicial de admin.

Mientras solucionamos el tema, puedes entrar en la base de datos y editar
la clave de admin. Solo recuerda, si lo haces con phpmyadmin, seleccionar
SHA como tipo de dato al escribir la nueva clave.
Si necesitas ayuda o no lo ves claro pone en contacto

Un saludo.

Miguel.

**Comment by rubenlh91** [comment]
Se ha solucionado el problema, había un error de sintaxis en el fichero SQL. Elimina la base de datos y el fichero config.php de la raíz de la Intranet, luego intenta de nuevo la instalación.
