### ISSUE TITLE
Problemas en la instalación

### ISSUE THREAD

**Issue by ahvega1984** [IESMonterroso/intranet#144]
Buenas, 
Hay un fallo en la instalación de la intranet, en el fichero:
config/tablas.sql

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `noticias`
--

DROP TABLE IF EXISTS `noticias`;
CREATE TABLE IF NOT EXISTS `noticias` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` text NOT NULL,
  `contenido` longtext NOT NULL,
  `autor` varchar(255) NOT NULL,
  `fechapub` datetime NOT NULL,
  `fechafin` date DEFAULT NULL,
  `categoria` varchar(200) NOT NULL,
  `vistas` INT UNSIGNED NOT NULL DEFAULT '0'
  `pagina` char(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci ;

Al final de la línea donde se crea el campo vistas falta una coma, debería quedar así:

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `noticias`
--

DROP TABLE IF EXISTS `noticias`;
CREATE TABLE IF NOT EXISTS `noticias` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` text NOT NULL,
  `contenido` longtext NOT NULL,
  `autor` varchar(255) NOT NULL,
  `fechapub` datetime NOT NULL,
  `fechafin` date DEFAULT NULL,
  `categoria` varchar(200) NOT NULL,
  `vistas` INT UNSIGNED NOT NULL DEFAULT '0',
  `pagina` char(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci ;

Un saludo y espero que suba a la rama master ya que nos hemos vuelto locos para poder instalarla.

**Comment by rubenlh91** [comment]
Solucionado! Gracias por el reporte del error.
