### ISSUE TITLE
Se muestra una query en /admin/tutoria/informe_memoria.php

### ISSUE THREAD

**Issue by ahvega1984** [IESMonterroso/intranet#145]
En admin/tutoria/informe_memoria.php se muestra una query:

`// Alumnos a final de Curso
 $SQL = "select * from alma where unidad = '".$_SESSION['mod_tutoria']['unidad']."'";
 $result = mysqli_query($db_con, $SQL);
 $num_acaban = mysqli_num_rows($result);

 // Alumnos que promocionan en Junio
 $SQL1 = "SELECT  * FROM `alma` where unidad = '".$_SESSION['mod_tutoria']['unidad']."' and (estadomatricula like 'Promociona%' OR estadomatricula like 'Obtiene tít%')";
 **echo $SQL1;**
 $result_promo = mysqli_query($db_con, $SQL1);`

**Comment by rubenlh91** [comment]
Solucionado el problema. Gracias por el aporte =)
