### ISSUE TITLE
Fallo al añadir ausencias

### ISSUE THREAD

**Issue by ahvega1984** [IESMonterroso/intranet#147]
La intranet falla a la hora de añadir ausencias, por lo que he visto la tabla ausencias, en el fichero admin/ausencias/index.php en la siguiente línea:

`$inserta = mysqli_query($db_con, "insert into ausencias VALUES ('', '$profesor_ausente', '$inicio1', '$fin1', '$horas', '', NOW(), '', '')");`

Creo que hay tres fallos de programación:

1. El primer campo es id (autoincrement) y ss intenta añadir una cadena vacía, esto yo lo solucionaría así:
`$inserta = mysqli_query($db_con, "insert into ausencias (profesor, inicio, fin, horas, tareas, ahora, archivo, Observaciones) VALUES ('$profesor', '$inicio1', '$fin1', '$horas', '$tareas', NOW(), '$nombre_archivo', '$observaciones')");`

2. El campo horas esta definido como entero pero se esta introduciendo una cadena, yo quitaría las comillas dobles:
 `$inserta = mysqli_query($db_con, "insert into ausencias (profesor, inicio, fin, horas, tareas, ahora, archivo, Observaciones) VALUES ('$profesor', '$inicio1', '$fin1', $horas, '$tareas', NOW(), '$nombre_archivo', '$observaciones')");`

3. Si no se seleccionan horas habría que quitar dicho campo del insert 
`if ($horas=='') { 
     $inserta = mysqli_query($db_con, "insert into ausencias (profesor, inicio, fin, tareas, ahora, archivo, Observaciones) VALUES ('$profesor', '$inicio1', '$fin1', '$tareas', NOW(), '$nombre_archivo', '$observaciones')");
} else {
     $inserta = mysqli_query($db_con, "insert into ausencias (profesor, inicio, fin, horas, tareas, ahora, archivo, Observaciones) VALUES ('$profesor', '$inicio1', '$fin1', $horas, '$tareas', NOW(), '$nombre_archivo', '$observaciones')");
}`

También he visto que algo mas complicado de resolver ya que es un fallo de modelado, según he entendido si un profesor falta de la primera a las tercera hora se almacenaría 123, y luego para mostrarlo se busca que existe el 1 o 2 o 3,... ¿que ocurre si existiese la hora 12? ¿Como se distingue entre el 12 o el 1 o el 2? Si yo marco primera y segunda hora, se me marca 1,2 y la hora 12. 

Lo normal sería poner dicho campo como texto y almacenar las horas separadas con "," y luego en php se manejas con las funciones explode e implode. 

En mi caso tenemos hasta 14 horas pero hay un bucle que solo llega hasta el 9:

`for ($i=1;$i<9;$i++) $horas .= ${hora.$i};`

Si necesitas ayuda dímelo.

Un saludo.

**Comment by ahvega1984** [comment]
Buenas otra vez, 

He creado un fork solventando el problema que te describo arriba, es el siguiente:
https://github.com/ahvega1984/intranet

Lo que he hecho es convertir el campo horas de la tabla ausencias en varchar y se almacenan las horas de las ausencias separados por comas, creo que lo he modificado en todos los sitios necesarios (ausencias y guardias).

He modificado los siguientes ficheros:

- admin/ausencias/index.php
- admin/ausencias/ausencias_profes.php
- admin/guardias/index_admin.php
- admin/guardias/procesa_guardias.php
- config/tablas.sql

Además he creado un pequeño script para convertir las ausencias ya introducidas con el nuevo formato:
config/actualizar_ausencias.php 

Supongo que lo tendrás que poner en la actualización. 

Un saludo.

**Comment by ahvega1984** [comment]
Buenos días, 
He visto que has incluido los cambios en el git pero la actualización no ha saltado en el centro, ¿es normal?
Un saludo y gracias por todo.

**Comment by mgarcia39** [comment]
Hola.

El código estaba siendo probado en el servidor del Monterroso. Todo
funciona perfectamente. En breve se actualizará la versión y aparecerá el
aviso en la intranet.
Gracias por tu aportación. Afectaba a una parte del código pendiente de
revisión.

Un saludo.

**Comment by ahvega1984** [comment]
Ok, muchas gracias. 

Lo que necesitéis comentarlo que si puedo os echo una mano.

**Comment by mgarcia39** [comment]
Toda ayuda es bienvenida...
