### ISSUE TITLE
Error al cambiar contraseña

### ISSUE THREAD

**Issue by cobyvg** [IESMonterroso/intranet#148]
En el archivo Usuarios.php se le aplica al campo password del POST la funcion limpiarinput con el parámetro "password" que  devuelve vacío si la contraseña no cumple ciertos requisitos.

El problema radica en que dicha comprobación también se hace para la contraseña actual y, en caso de tratarse de un reset, cuya contraseña por defecto es el DNI del profesor, el rsultado es vacio y no deja poner la contraseña actual.

El comportamiento es que el usuario puede logearse pero no puede cambiar a contraseña por otra más segura. 

La solución que hemos aplicado es no utilizar la funcion limpiarinput con el campo de la contraseña actual, ya que se entiende que, o bien ya pasó esa verificación con anterioridad o bien se trata de un usuario que ha sido reseteado y quiere establecer su porpia contrseña.

**Comment by rubenlh91** [comment]
Solucionado. Gracias por el aporte.
