### ISSUE TITLE
Con perfil DACE no puedo crear Nueva Actividad Extraescolar

### ISSUE THREAD

**Issue by jcapsal840** [IESMonterroso/intranet#150]
La compañera que tiene perfil DACE en la intranet del IES Huelin lleva al menos un par de semanas que no puede crear una nueva actividad extraescolar.
No sabemos el motivo de que ahora no le deje cuando antes sí. Podría ser por las fechas. Otros años no le había pasado estoy tan pronto.
Está creando las actividades entrando con el usuario de un compañero/a con perfil Dirección. Así sí deja hacerlo.

**Comment by mgarcia39** [comment]
No encuentro problema alguno al registrar actividades extraescolares con el perfil de nuestro DACE. Este perfil debe estar registrado en el perfil del profesor correspondiente en _**Administración de la intranet/profesores/Perfiles de los profesores**_.
Hay que tener en cuenta la opción de configuración del calendario que permite bloquear el registro de las actividades extraescolares durante el tercer trimestre. Se puede cambiar _**/calendario/preferencias.php**_

**Comment by jcapsal840** [comment]
Se me había olvidado decir que he comprobado las preferencias del calendario y están las 3 opciones con el valor Permitir, como puede ver en la siguiente captura:

![Captura Preferencias del Calendario](https://user-images.githubusercontent.com/105362108/167924923-7dcbcc64-84df-4b10-839b-01281212649a.PNG)

**Comment by jcapsal840** [comment]
Hola de nuevo. Ya se ha solucionado.
Ha tenido que ser por algún conflicto entre las tablas de la BD. Y ahora funciona bien.
Esperemos que no se vuelva a producir.
Probé las 2 soluciones que me planteabas. La primera funcionaba bien con otro profesor/ra. La 2ª opción estaba bien, en la tabla tenía puesto el número 5 para mi compañera.
Muchas gracias. Saludos.
