### ISSUE TITLE
Fallo al Registrar Calificaciones en Evaluación de Pendientes

### ISSUE THREAD

**Issue by jcapsal840** [IESMonterroso/intranet#151]
Hemos detectado en esta última evaluación que al querer registrar una calificación de pendientes sale un fallo en una consulta a una BD. En la 1ª y 2ª evaluación no hubo ningún problema para poder introducir las notas de pendientes.

Dejo captura de pantalla en el que se indica el error que aparece en pantalla:

![Screenshot_20220510-124204_Samsung Internet](https://user-images.githubusercontent.com/105362108/167912278-e361454c-353f-4da5-88b1-df4be464d182.jpg)

**Comment by mgarcia39** [comment]
Parece que la versión de la aplicación del IES Huelin no está actualizada. El código de registro de notas para pendientes (si nos referimos a ./admin/evaluación_pendientes/lista_pendientes.php; no veo la di¡rección completa en la imagen) no contiene ese código desde hace ya algún tiempo.

**Comment by jcapsal840** [comment]
Hola de nuevo.
Le paso captura donde puede ver que la aplicación me dice que está actualizada.  Es la versión 4.62.0.
![Captura Actualización de la Intranet](https://user-images.githubusercontent.com/105362108/167924185-9a7715f6-620b-4536-9281-de72c028076d.PNG)

Y le vuelvo a mandar captura con el fallo que me sale a mí con el perfil de administrador al Registrar una Calificación de Pendientes.
![Captura Fallo al Registrar Evaluación de pendientes](https://user-images.githubusercontent.com/105362108/167924496-4c77c9f9-55bf-48e9-89ac-134175bbc443.PNG)

**Comment by mgarcia39** [comment]
Corregido finalmente.

**Comment by rubenlh91** [comment]
Se ha publicado una nueva versión de la Intranet que soluciona el problema.

**Comment by jcapsal840** [comment]
Muchas gracias por la inmediatez
