### ISSUE TITLE
Error al Instalar

### ISSUE THREAD

**Issue by KratosSama** [IESMonterroso/intranet#154]
Fatal error: Uncaught Error: Call to undefined function mysqli_connect() in C:\Apache24\htdocs\intranet\config\index.php:292 Stack trace: #0 {main} thrown in C:\Apache24\htdocs\intranet\config\index.php on line 292

Me sale ese error al tratar de instalar el software, en un principio pensé que eran mis credenciales del MySQL, pero ya he probado creando otros usuario y sigo teniendo el mismo error.

**Comment by rubenlh91** [comment]
La aplicación web debe correr sobre un sistema Linux.
