### ISSUE TITLE
PHP Code Execution in $_tarea - tarea.php

### ISSUE THREAD

**Issue by lockedbyte** [IESMonterroso/intranet#40]
An attacker can inject code into preg_replace() to be executed.

`$_tarea = preg_replace('/(<[^>]+) style=".*?"/i', '$1', $_POST['tarea']);`

Vulnerable usage of preg_replace():

```
$texto = "Esto es un texto";
$out = preg_replace("/texto/", "codigo", $texto);
```

Secure usage of preg_replace():

```
$texto = "Esto es un texto";
$out = preg_replace("#" . preg_quote("texto", "#") . "#", "codigo", $texto);
```

**Comment by attritionorg** [comment]
@lockedbyte was the content deleted for security reasons?
